export const ICON_MAPPINGS = {
  amazonaws: "AWS",
  android: "Android",
  androidstudio: "Android Studio",
  arduino: "Arduino",
  babel: "Babel",
  bitbucket: "Bit Bucket",
  bootstrap: "Bootstrap",
  css3: "CSS3",
  d3dotjs: "D3.js",
  digitalocean: "Digital Ocean",
  docker: "Docker",
  dotenv: ".Env",
  express: "Express.js",
  figma: "Figma",
  git: "Git",
  github: "GitHub",
  gitlab: "GitLab",
  googlecloud: "Google Cloud",
  graphql: "GraphQL",
  heroku: "Heroku",
  html5: "HTML5",
  jamstack: "JAMstack",
  javascript: "JavaScript",
  jest: "Jest",
  jira: "Jira",
  json: "JSON",
  kubernetes: "Kubernetes",
  microsoftazure: "Microsoft Azure",
  mongodb: "MongoDB",
  mui: "Material-UI",
  mysql: "MySQL",
  netlify: "Netlify",
  nextdotjs: "Next.js",
  nodedotjs: "Node.js",
  npm: "npm",
  php: "PHP",
  playwright: "Playwright",
  pnpm: "pnpm",
  postgresql: "PostgreSQL",
  puppeteer: "Puppeteer",
  python: "Python",
  react: "React",
  socketdotio: "Socket.IO",
  svelte: "Svelte",
  swift: "Swift",
  threedotjs: "Three.js",
  typescript: "TypeScript",
  vercel: "Vercel",
  visualstudiocode: "Visual Studio Code",
  webpack: "webpack",
  yarn: "Yarn",
};
